# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppWithDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppWithDB
pod 'SQLite.swift', '~> 0.12.0'
end
